services:
  db:
    build:
      context: ./supabase
      dockerfile: Dockerfile.db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-0d3c46d9d1e8fd90e4a16ee5b8659990}
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      JWT_SECRET: ${JWT_SECRET:-ca6b2ff5d35a69c5fce51c0bb56852aee8d88740a64b1d5afc2aa33fc6c157b2}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 10s
      retries: 10

  rest:
    image: postgrest/postgrest:v12.2.0
    restart: always
    depends_on:
      - db # Startet sobald der DB-Container existiert, wartet nicht auf "Healthy"
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD:-0d3c46d9d1e8fd90e4a16ee5b8659990}@db:5432/postgres
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_DB_EXTRA_SEARCH_PATH: public
      PGRST_JWT_SECRET: ${JWT_SECRET:-ca6b2ff5d35a69c5fce51c0bb56852aee8d88740a64b1d5afc2aa33fc6c157b2}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - rest

  realtime:
    image: ghcr.io/supabase/realtime:v2.78.11
    restart: always
    depends_on:
      - db
    environment:
      - PORT=4000
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD:-0d3c46d9d1e8fd90e4a16ee5b8659990}
      - DB_PORT=5432
      - DB_SSL=false
      - JWT_SECRET=${JWT_SECRET:-ca6b2ff5d35a69c5fce51c0bb56852aee8d88740a64b1d5afc2aa33fc6c157b2}
      - REPLICATION_MODE=PUBLICATION
      - DB_ENC_KEY=${REALTIME_ENCRYPTION_KEY:-d59dfcf1ced0152a}

volumes:
  db_data:
